"""Tests for documentation generation."""

import json
from pathlib import Path

import pytest

from scripts.generate_docs import (
    component_counts,
    count_patterns,
    generate_dashboard_md,
    generate_stack_catalog,
    generate_getting_started,
    scan_claude_dir,
    update_readme_counts,
)


class TestCountPatterns:
    def test_counts_correctly(self, sample_registry):
        counts = count_patterns(sample_registry)
        assert counts["total"] == 2
        assert counts["core"] == 2
        assert counts["by_type"]["skill"] == 1
        assert counts["by_type"]["hook"] == 1


class TestGenerateDashboardMd:
    def test_has_required_sections(self, sample_registry):
        md = generate_dashboard_md(sample_registry, [], {})
        assert "# Claude Best Practices Hub" in md
        assert "At a Glance" in md
        assert "Pattern Inventory" in md

    def test_includes_pattern_count(self, sample_registry):
        md = generate_dashboard_md(sample_registry, [], {})
        assert "2" in md


class TestGenerateStackCatalog:
    def test_lists_stacks(self, tmp_path):
        """Stack catalog now uses .claude/ dir with prefix convention."""
        claude_dir = tmp_path / ".claude"
        (claude_dir / "agents").mkdir(parents=True)
        (claude_dir / "agents" / "android-compose.md").write_text("# Android")
        (claude_dir / "skills" / "android-run-tests").mkdir(parents=True)
        (claude_dir / "skills" / "android-run-tests" / "SKILL.md").write_text("# Tests")
        catalog = generate_stack_catalog(claude_dir)
        assert "Android" in catalog
        assert "android-" in catalog


class TestGenerateGettingStarted:
    def test_has_quick_start(self):
        counts = {"agents": 39, "skills": 164, "rules": 47, "hooks": 11}
        doc = generate_getting_started("abhayla/claude-best-practices", ["android-compose"], counts)
        assert "Quick Start" in doc
        assert "android-compose" in doc

    def test_uses_real_counts_not_hardcoded(self):
        """Regression: the old generator hardcoded 13/26/10; counts must come from disk."""
        counts = {"agents": 39, "skills": 164, "rules": 47, "hooks": 11}
        doc = generate_getting_started("abhayla/claude-best-practices", [], counts)
        assert "| Agents | 39 |" in doc
        assert "| Skills | 164 |" in doc
        assert "| Rules | 47 |" in doc
        assert "| Hooks | 11 |" in doc
        assert "13" not in doc and "| 26 |" not in doc


class TestComponentCounts:
    def _build_claude_dir(self, tmp_path):
        claude_dir = tmp_path / ".claude"
        (claude_dir / "agents").mkdir(parents=True)
        (claude_dir / "agents" / "code-reviewer.md").write_text("# x")
        (claude_dir / "agents" / "README.md").write_text("# docs, not an agent")
        (claude_dir / "skills" / "tdd").mkdir(parents=True)
        (claude_dir / "skills" / "tdd" / "SKILL.md").write_text("# x")
        (claude_dir / "rules").mkdir()
        (claude_dir / "rules" / "testing.md").write_text("# x")
        (claude_dir / "hooks").mkdir()
        (claude_dir / "hooks" / "auto-format.sh").write_text("#!/bin/sh")
        (claude_dir / "hooks" / "README.md").write_text("# docs, not a hook")
        return claude_dir

    def test_excludes_readme_from_every_kind(self, tmp_path):
        claude_dir = self._build_claude_dir(tmp_path)
        inv = scan_claude_dir(claude_dir)
        assert inv["agents"] == ["code-reviewer"]
        assert inv["hooks"] == ["auto-format.sh"]

    def test_counts_each_kind(self, tmp_path):
        claude_dir = self._build_claude_dir(tmp_path)
        counts = component_counts(claude_dir)
        assert counts == {"agents": 1, "skills": 1, "rules": 1, "hooks": 1}


class TestUpdateReadmeCounts:
    MARKERS = (
        "intro text\n"
        "<!-- COUNTS:START (auto-generated by scripts/generate_docs.py — do not edit by hand) -->\n"
        "| Component | Count | Description |\n"
        "| **Agents** | 1 | old |\n"
        "<!-- COUNTS:END -->\n"
        "trailing text\n"
    )

    def test_replaces_block_and_preserves_surrounding_prose(self, tmp_path):
        readme = tmp_path / "README.md"
        readme.write_text(self.MARKERS, encoding="utf-8")
        changed = update_readme_counts(readme, {"agents": 39, "skills": 164, "rules": 47, "hooks": 11})
        out = readme.read_text(encoding="utf-8")
        assert changed is True
        assert out.startswith("intro text")
        assert out.endswith("trailing text\n")
        assert "| **Agents** | 39 |" in out
        assert "| **Skills** | 164 |" in out

    def test_idempotent_second_run_is_noop(self, tmp_path):
        readme = tmp_path / "README.md"
        readme.write_text(self.MARKERS, encoding="utf-8")
        counts = {"agents": 39, "skills": 164, "rules": 47, "hooks": 11}
        update_readme_counts(readme, counts)
        assert update_readme_counts(readme, counts) is False

    def test_no_markers_is_noop(self, tmp_path):
        readme = tmp_path / "README.md"
        readme.write_text("no markers here\n", encoding="utf-8")
        assert update_readme_counts(readme, {"agents": 1, "skills": 1, "rules": 1, "hooks": 1}) is False
