"""Sync hub patterns to registered project repos via PRs."""

import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import yaml

from scripts.bootstrap import STACK_PREFIXES


def load_repos_config(config_path: Path) -> list[dict]:
    """Load repos from config/repos.yml."""
    if not config_path.exists():
        return []
    with open(config_path, encoding="utf-8") as f:
        data = yaml.safe_load(f)
    return data.get("repos", [])


def get_repo_sync_config(repo: str) -> Optional[dict]:
    """Fetch .claude/sync-config.yml from a GitHub repo via API."""
    try:
        result = subprocess.run(
            ["gh", "api", f"repos/{repo}/contents/.claude/sync-config.yml",
             "--jq", ".content", "-H", "Accept: application/vnd.github.v3.raw"],
            capture_output=True, text=True, timeout=30,
        )
        if result.returncode == 0 and result.stdout.strip():
            return yaml.safe_load(result.stdout)
    except Exception:
        pass
    return None


def check_existing_pr(repo: str, branch: str) -> bool:
    """Check if there's already an open PR for the sync branch."""
    try:
        result = subprocess.run(
            ["gh", "pr", "list", "--repo", repo, "--head", branch, "--state", "open", "--json", "number"],
            capture_output=True, text=True, timeout=30,
        )
        if result.returncode == 0:
            prs = json.loads(result.stdout)
            return len(prs) > 0
    except Exception:
        pass
    return False


def pattern_matches_stacks(pattern_name: str, selected_stacks: list[str], category: str) -> bool:
    """Check if a pattern should be synced to a project based on its stacks.

    Uses prefix-based matching: a pattern with name 'fastapi-backend' matches
    the 'fastapi-python' stack because it starts with the 'fastapi-' prefix.
    Core patterns (no stack prefix) always match.
    """
    # Build allowed prefixes from selected stacks
    allowed_prefixes = set()
    for stack in selected_stacks:
        prefix = STACK_PREFIXES.get(stack)
        if prefix:
            allowed_prefixes.add(prefix)

    # All known prefixes
    all_prefixes = set(STACK_PREFIXES.values())

    # Check if this pattern is stack-specific
    is_stack_specific = any(pattern_name.startswith(p) for p in all_prefixes)

    if not is_stack_specific:
        # Core pattern — always matches
        return True

    # Stack-specific — check if its prefix is allowed
    return any(pattern_name.startswith(p) for p in allowed_prefixes)


def build_sync_diff(hub_registry: dict, remote_config: dict) -> list[dict]:
    """Compute which patterns need syncing to a project."""
    selected_stacks = remote_config.get("selected_stacks", [])

    updates = []
    for name, entry in hub_registry.items():
        if name.startswith("_") or not isinstance(entry, dict):
            continue
        category = entry.get("category", "core")
        if not pattern_matches_stacks(name, selected_stacks, category):
            continue
        updates.append({
            "name": name,
            "type": entry.get("type"),
            "version": entry.get("version"),
            "category": category,
            "contributed_by": entry.get("contributed_by", []),
        })
    return updates


def build_pr_body(updates: list[dict], repo: str) -> str:
    """Build PR body with attribution for patterns that came from downstream projects."""
    lines = ["## Hub Pattern Sync", ""]
    lines.append(f"Syncing {len(updates)} patterns from the hub to `{repo}`.")
    lines.append("")

    # Group by type
    by_type: dict[str, list[dict]] = {}
    for u in updates:
        by_type.setdefault(u.get("type", "unknown"), []).append(u)

    for ptype, items in sorted(by_type.items()):
        lines.append(f"### {ptype.title()}s ({len(items)})")
        for item in sorted(items, key=lambda x: x["name"]):
            lines.append(f"- **{item['name']}** v{item.get('version', '?')}")
        lines.append("")

    # Attribution section — show which patterns were generalized from project contributions
    contributed = [u for u in updates if u.get("contributed_by")]
    if contributed:
        lines.append("### Attribution")
        lines.append("")
        lines.append("These patterns were generalized from synthesized patterns across multiple projects:")
        lines.append("")
        for item in contributed:
            sources = ", ".join(item["contributed_by"])
            lines.append(f"- **{item['name']}** — contributed by: {sources}")
        lines.append("")

    lines.append("---")
    lines.append("Auto-generated by [claude-best-practices](https://github.com/abhayla/claude-best-practices) hub sync.")
    return "\n".join(lines)


def create_sync_pr(repo: str, branch: str, updates: list[dict]) -> Optional[str]:
    """Create a sync PR on the target repo with attribution."""
    body = build_pr_body(updates, repo)
    try:
        result = subprocess.run(
            ["gh", "pr", "create", "--repo", repo,
             "--head", branch,
             "--title", f"chore: sync {len(updates)} hub patterns",
             "--body", body],
            capture_output=True, text=True, timeout=60,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        pass
    return None


# --- Telemetry: Provision Manifest & Adoption Scanning ---


def _pattern_rel_path(name: str, resource_type: str) -> str:
    """Compute the relative path within .claude/ for a pattern."""
    if resource_type == "skill":
        return f"skills/{name}/SKILL.md"
    elif resource_type == "agent":
        return f"agents/{name}.md"
    elif resource_type == "rule":
        return f"rules/{name}.md"
    return f"{resource_type}s/{name}"


def generate_provision_manifest(updates: list[dict]) -> dict:
    """Generate a sync manifest recording what was provisioned and when.

    This manifest is written to the target project during sync so that
    future syncs can compute adoption signals (which patterns were kept
    vs deleted).
    """
    now = datetime.now(timezone.utc)
    today = now.strftime("%Y-%m-%d")
    files = {}

    for update in updates:
        name = update["name"]
        rtype = update.get("type", "skill")
        rel_path = _pattern_rel_path(name, rtype)
        files[rel_path] = {
            "provisioned_date": today,
            "version": update.get("version", "0.0.0"),
        }

    return {
        "_meta": {
            "version": "1.0.0",
            "hub_repo": "abhayla/claude-best-practices",
            "created": now.isoformat(),
            "last_sync": now.isoformat(),
        },
        "files": files,
    }


def scan_remote_adoption(
    manifest: dict, remote_files: list[str]
) -> dict[str, dict]:
    """Compute adoption signals by comparing manifest against remote file listing.

    Args:
        manifest: The sync manifest from the project (what was provisioned).
        remote_files: List of file paths that currently exist in the project's
                      .claude/ directory (e.g., from GitHub API tree listing).

    Returns:
        Dict mapping pattern name to {status, retention_days, provisioned_date}.
    """
    files = manifest.get("files", {})
    if not files:
        return {}

    # Normalize remote files to be relative to .claude/
    remote_set = set()
    for f in remote_files:
        cleaned = f.replace("\\", "/")
        if cleaned.startswith(".claude/"):
            cleaned = cleaned[len(".claude/"):]
        remote_set.add(cleaned)

    now = datetime.now(timezone.utc)
    result = {}

    for rel_path, meta in files.items():
        match = re.match(r"^(skills|agents|rules)/([^/]+)", rel_path)
        if not match:
            continue

        resource_type, pattern_name = match.groups()
        if resource_type in ("agents", "rules"):
            pattern_name = pattern_name.removesuffix(".md")

        exists = rel_path in remote_set

        provisioned_date = meta.get("provisioned_date")
        retention_days = 0
        if provisioned_date:
            try:
                pdate = datetime.fromisoformat(provisioned_date)
                if pdate.tzinfo is None:
                    pdate = pdate.replace(tzinfo=timezone.utc)
                retention_days = max(0, (now - pdate).days)
            except (ValueError, TypeError):
                retention_days = 0

        result[pattern_name] = {
            "status": "adopted" if exists else "deleted",
            "retention_days": retention_days,
            "provisioned_date": provisioned_date,
        }

    return result
